import { OptionsMap } from "./types";

export const options: OptionsMap = {
  obudowa: [
    "Heban polerowany",
    "Palisander",
    "Orzech amerykański",
    "Orzech włoski",
    "Orzech kaukaski",
    "Orzech czeczot",
    "Bubinga",
    "Mahoń pasiak",
    "Mahoń piramidalny",
    "Biały poliester",
    "Czarny poliester",
  ],
  akustyka: [
    "Dno rezonansowe Strunz",
    "Dno rezonansowe Chiresse",
    "Lakierowanie dna rezonansowego mat",
    "Lakierowanie dna rezonansowego połysk",
    "Mostki rezonansowe klon",
    "Mostki rezonansowe buk",
    "Kolor ramy złoty",
    "Kolor ramy srebrny",
    "Struny stalowe Roslau",
    "Struny stalowe Paulelo",
    "Struny basowe Heller",
    "Struny basowe SAP Renovation",
    "Kołki stroikowe niklowane",
    "Kołki stroikowe Blau",
    "Kolor sukna czerwony",
    "Kolor sukna biały",
    "Kolor sukna czarny",
  ],
  mechanizm: [
    "Klawiatura Alaudis SAP Renovation",
    "Klawiatura Kluge",
    "Mechanizm Alaudis SAP Renovation",
    "Mechanizm Renner",
    "Mechanizm Abbel",
    "Młotki Alaudis",
    "Młotki Renner",
    "Młotki Abbel",
    "Tłumiki Alaudis",
    "Tłumiki Renner",
    "Tłumiki Abbel",
  ],
};

export const groupMap: Record<string, string> = {
  "Dno rezonansowe Strunz": "dno",
  "Dno rezonansowe Chiresse": "dno",
  "Lakierowanie dna rezonansowego mat": "lakierDno",
  "Lakierowanie dna rezonansowego połysk": "lakierDno",
  "Mostki rezonansowe klon": "mostki",
  "Mostki rezonansowe buk": "mostki",
  "Struny stalowe Roslau": "struny",
  "Struny stalowe Paulelo": "struny",
  "Struny basowe Heller": "basowe",
  "Struny basowe SAP Renovation": "basowe",
  "Kołki stroikowe niklowane": "kolki",
  "Kołki stroikowe Blau": "kolki",
  "Kolor sukna czerwony": "sukno",
  "Kolor sukna biały": "sukno",
  "Kolor sukna czarny": "sukno",
  "Klawiatura Alaudis SAP Renovation": "klawiatura",
  "Klawiatura Kluge": "klawiatura",
  "Mechanizm Alaudis SAP Renovation": "mechanizm",
  "Mechanizm Renner": "mechanizm",
  "Mechanizm Abbel": "mechanizm",
  "Młotki Alaudis": "mlotki",
  "Młotki Renner": "mlotki",
  "Młotki Abbel": "mlotki",
  "Tłumiki Alaudis": "tlumiki",
  "Tłumiki Renner": "tlumiki",
  "Tłumiki Abbel": "tlumiki",
};

export const previewImageMap: Record<string, string> = {
  // 🔥 OBUDOWA
  "Heban polerowany": "/konfigurator/obudowa/heban-polerowany.jpg",
  "Palisander": "/konfigurator/obudowa/palisander.jpg",
  "Orzech amerykański": "/konfigurator/obudowa/orzech-amerykanski.jpg",
  "Orzech włoski": "/konfigurator/obudowa/orzech-wloski.jpg",
  "Orzech kaukaski": "/konfigurator/obudowa/orzech-kaukaski.jpg",
  "Orzech czeczot": "/konfigurator/obudowa/orzech-czeczot.jpg",
  "Bubinga": "/konfigurator/obudowa/bubinga.jpg",
  "Mahoń pasiak": "/konfigurator/obudowa/mahon-pasiak.jpg",
  "Mahoń piramidalny": "/konfigurator/obudowa/mahon-piramidalny.jpg",
  "Biały poliester": "/konfigurator/obudowa/bialy-poliester.jpg",
  "Czarny poliester": "/konfigurator/obudowa/czarny-poliester.jpg",

  // 🔥 AKUSTYKA
  "Mostki rezonansowe klon": "/konfigurator/akustyka/mostki-klon.jpg",
  "Mostki rezonansowe buk": "/konfigurator/akustyka/mostki-buk.jpg",
  "Dno rezonansowe Strunz": "/konfigurator/akustyka/dno-strunz.jpg",
  "Dno rezonansowe Chiresse": "/konfigurator/akustyka/dno-chiresse.jpg",
  "Lakierowanie dna rezonansowego mat": "/konfigurator/akustyka/lakier-mat.jpg",
  "Lakierowanie dna rezonansowego połysk": "/konfigurator/akustyka/lakier-polysk.jpg",

  // 🔥 MECHANIZM
  "Młotki Alaudis": "/konfigurator/mechanizm/mlotki-alaudis.jpg",
  "Młotki Renner": "/konfigurator/mechanizm/mlotki-renner.jpg",
  "Młotki Abbel": "/konfigurator/mechanizm/mlotki-abbel.jpg",
  "Mechanizm Alaudis SAP Renovation": "/konfigurator/mechanizm/mechanizm-alaudis.jpg",
  "Mechanizm Renner": "/konfigurator/mechanizm/mechanizm-renner.jpg",
  "Mechanizm Abbel": "/konfigurator/mechanizm/mechanizm-abbel.jpg",
};

export const defaultPreviewImage = "/hero.jpg";
